# Generated by Django 5.0.2 on 2024-02-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0002_unit_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='staff',
        ),
        migrations.AddField(
            model_name='unit',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
