# Generated by Django 5.0.2 on 2024-02-27 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnitAssignment',
        ),
    ]
